FROM nginx:latest

## Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

FROM npm
RUN npm run build.prod
RUN docker build -t programmer-webui .

FROM nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY dist/prod /usr/share/nginx/html